//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MSYS.Web.StoreService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StoreServiceInterfaceServiceSoapBinding", Namespace="http://webservice.dhcc.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseVO))]
    public partial class StoreServiceInterfaceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback yuanfuCgrkOperationCompleted;
        
        private System.Threading.SendOrPostCallback yuanliaoInAndOut4ws_03OperationCompleted;
        
        private System.Threading.SendOrPostCallback insertMaterialPurchaseinInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StoreServiceInterfaceService() {
            this.Url = global::MSYS.Web.Properties.Settings.Default.MSYS_Web_StoreService_StoreServiceInterfaceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event yuanfuCgrkCompletedEventHandler yuanfuCgrkCompleted;
        
        /// <remarks/>
        public event yuanliaoInAndOut4ws_03CompletedEventHandler yuanliaoInAndOut4ws_03Completed;
        
        /// <remarks/>
        public event insertMaterialPurchaseinInfoCompletedEventHandler insertMaterialPurchaseinInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.dhcc.com/", ResponseNamespace="http://webservice.dhcc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string yuanfuCgrk([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] poOrderAllVO arg0) {
            object[] results = this.Invoke("yuanfuCgrk", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void yuanfuCgrkAsync(poOrderAllVO arg0) {
            this.yuanfuCgrkAsync(arg0, null);
        }
        
        /// <remarks/>
        public void yuanfuCgrkAsync(poOrderAllVO arg0, object userState) {
            if ((this.yuanfuCgrkOperationCompleted == null)) {
                this.yuanfuCgrkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnyuanfuCgrkOperationCompleted);
            }
            this.InvokeAsync("yuanfuCgrk", new object[] {
                        arg0}, this.yuanfuCgrkOperationCompleted, userState);
        }
        
        private void OnyuanfuCgrkOperationCompleted(object arg) {
            if ((this.yuanfuCgrkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.yuanfuCgrkCompleted(this, new yuanfuCgrkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.dhcc.com/", ResponseNamespace="http://webservice.dhcc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsRespond yuanliaoInAndOut4ws_03([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] materInAndOutVO arg0) {
            object[] results = this.Invoke("yuanliaoInAndOut4ws_03", new object[] {
                        arg0});
            return ((wsRespond)(results[0]));
        }
        
        /// <remarks/>
        public void yuanliaoInAndOut4ws_03Async(materInAndOutVO arg0) {
            this.yuanliaoInAndOut4ws_03Async(arg0, null);
        }
        
        /// <remarks/>
        public void yuanliaoInAndOut4ws_03Async(materInAndOutVO arg0, object userState) {
            if ((this.yuanliaoInAndOut4ws_03OperationCompleted == null)) {
                this.yuanliaoInAndOut4ws_03OperationCompleted = new System.Threading.SendOrPostCallback(this.OnyuanliaoInAndOut4ws_03OperationCompleted);
            }
            this.InvokeAsync("yuanliaoInAndOut4ws_03", new object[] {
                        arg0}, this.yuanliaoInAndOut4ws_03OperationCompleted, userState);
        }
        
        private void OnyuanliaoInAndOut4ws_03OperationCompleted(object arg) {
            if ((this.yuanliaoInAndOut4ws_03Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.yuanliaoInAndOut4ws_03Completed(this, new yuanliaoInAndOut4ws_03CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.dhcc.com/", ResponseNamespace="http://webservice.dhcc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string insertMaterialPurchaseinInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contentXml) {
            object[] results = this.Invoke("insertMaterialPurchaseinInfo", new object[] {
                        contentXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertMaterialPurchaseinInfoAsync(string contentXml) {
            this.insertMaterialPurchaseinInfoAsync(contentXml, null);
        }
        
        /// <remarks/>
        public void insertMaterialPurchaseinInfoAsync(string contentXml, object userState) {
            if ((this.insertMaterialPurchaseinInfoOperationCompleted == null)) {
                this.insertMaterialPurchaseinInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertMaterialPurchaseinInfoOperationCompleted);
            }
            this.InvokeAsync("insertMaterialPurchaseinInfo", new object[] {
                        contentXml}, this.insertMaterialPurchaseinInfoOperationCompleted, userState);
        }
        
        private void OninsertMaterialPurchaseinInfoOperationCompleted(object arg) {
            if ((this.insertMaterialPurchaseinInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertMaterialPurchaseinInfoCompleted(this, new insertMaterialPurchaseinInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class poOrderAllVO {
        
        private string bzField;
        
        private string bzNameField;
        
        private string cgbmField;
        
        private string cgbmNameField;
        
        private string cgyField;
        
        private string cgyNameField;
        
        private string cwarehouseNameField;
        
        private string cwarehouseidField;
        
        private string ddrqField;
        
        private string gysField;
        
        private string gysNameField;
        
        private icPurchaseinBVO[] icPurchaseinBVOListField;
        
        private string idField;
        
        private string isNcField;
        
        private string kpgysField;
        
        private string kpgysNameField;
        
        private string materTypeField;
        
        private string statusField;
        
        private double sumNumField;
        
        private double sunPriceField;
        
        private string zdkslbField;
        
        private string zdslField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bz {
            get {
                return this.bzField;
            }
            set {
                this.bzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bzName {
            get {
                return this.bzNameField;
            }
            set {
                this.bzNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cgbm {
            get {
                return this.cgbmField;
            }
            set {
                this.cgbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cgbmName {
            get {
                return this.cgbmNameField;
            }
            set {
                this.cgbmNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cgy {
            get {
                return this.cgyField;
            }
            set {
                this.cgyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cgyName {
            get {
                return this.cgyNameField;
            }
            set {
                this.cgyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cwarehouseName {
            get {
                return this.cwarehouseNameField;
            }
            set {
                this.cwarehouseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cwarehouseid {
            get {
                return this.cwarehouseidField;
            }
            set {
                this.cwarehouseidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ddrq {
            get {
                return this.ddrqField;
            }
            set {
                this.ddrqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gys {
            get {
                return this.gysField;
            }
            set {
                this.gysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gysName {
            get {
                return this.gysNameField;
            }
            set {
                this.gysNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("icPurchaseinBVOList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public icPurchaseinBVO[] icPurchaseinBVOList {
            get {
                return this.icPurchaseinBVOListField;
            }
            set {
                this.icPurchaseinBVOListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isNc {
            get {
                return this.isNcField;
            }
            set {
                this.isNcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kpgys {
            get {
                return this.kpgysField;
            }
            set {
                this.kpgysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kpgysName {
            get {
                return this.kpgysNameField;
            }
            set {
                this.kpgysNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materType {
            get {
                return this.materTypeField;
            }
            set {
                this.materTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double sumNum {
            get {
                return this.sumNumField;
            }
            set {
                this.sumNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double sunPrice {
            get {
                return this.sunPriceField;
            }
            set {
                this.sunPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zdkslb {
            get {
                return this.zdkslbField;
            }
            set {
                this.zdkslbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zdsl {
            get {
                return this.zdslField;
            }
            set {
                this.zdslField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class icPurchaseinBVO {
        
        private string cgeneralbidField;
        
        private string clocationidField;
        
        private string crownoField;
        
        private string cunitidField;
        
        private string dbizdateField;
        
        private string localNameField;
        
        private string materialCodeField;
        
        private string materialNameField;
        
        private string materialspecField;
        
        private string materialtypeField;
        
        private double nmnyField;
        
        private bool nmnyFieldSpecified;
        
        private double nnumField;
        
        private bool nnumFieldSpecified;
        
        private double nshouldnumField;
        
        private bool nshouldnumFieldSpecified;
        
        private double ntaxField;
        
        private bool ntaxFieldSpecified;
        
        private double taxPriceField;
        
        private bool taxPriceFieldSpecified;
        
        private string unitCodeField;
        
        private string unitNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cgeneralbid {
            get {
                return this.cgeneralbidField;
            }
            set {
                this.cgeneralbidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clocationid {
            get {
                return this.clocationidField;
            }
            set {
                this.clocationidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string crowno {
            get {
                return this.crownoField;
            }
            set {
                this.crownoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cunitid {
            get {
                return this.cunitidField;
            }
            set {
                this.cunitidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dbizdate {
            get {
                return this.dbizdateField;
            }
            set {
                this.dbizdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string localName {
            get {
                return this.localNameField;
            }
            set {
                this.localNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materialName {
            get {
                return this.materialNameField;
            }
            set {
                this.materialNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materialspec {
            get {
                return this.materialspecField;
            }
            set {
                this.materialspecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materialtype {
            get {
                return this.materialtypeField;
            }
            set {
                this.materialtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double nmny {
            get {
                return this.nmnyField;
            }
            set {
                this.nmnyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nmnySpecified {
            get {
                return this.nmnyFieldSpecified;
            }
            set {
                this.nmnyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double nnum {
            get {
                return this.nnumField;
            }
            set {
                this.nnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nnumSpecified {
            get {
                return this.nnumFieldSpecified;
            }
            set {
                this.nnumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double nshouldnum {
            get {
                return this.nshouldnumField;
            }
            set {
                this.nshouldnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nshouldnumSpecified {
            get {
                return this.nshouldnumFieldSpecified;
            }
            set {
                this.nshouldnumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ntax {
            get {
                return this.ntaxField;
            }
            set {
                this.ntaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ntaxSpecified {
            get {
                return this.ntaxFieldSpecified;
            }
            set {
                this.ntaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double taxPrice {
            get {
                return this.taxPriceField;
            }
            set {
                this.taxPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxPriceSpecified {
            get {
                return this.taxPriceFieldSpecified;
            }
            set {
                this.taxPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unitCode {
            get {
                return this.unitCodeField;
            }
            set {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class wsRespond {
        
        private string descField;
        
        private string orderNoField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tShopMaterInoutSub))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class baseVO {
        
        private int drawField;
        
        private bool drawFieldSpecified;
        
        private int lengthField;
        
        private bool lengthFieldSpecified;
        
        private int pageNumField;
        
        private bool pageNumFieldSpecified;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int draw {
            get {
                return this.drawField;
            }
            set {
                this.drawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool drawSpecified {
            get {
                return this.drawFieldSpecified;
            }
            set {
                this.drawFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageNum {
            get {
                return this.pageNumField;
            }
            set {
                this.pageNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumSpecified {
            get {
                return this.pageNumFieldSpecified;
            }
            set {
                this.pageNumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class tShopMaterInoutSub : baseVO {
        
        private string auditMarkField;
        
        private double batchNumberField;
        
        private bool batchNumberFieldSpecified;
        
        private double costpriceField;
        
        private bool costpriceFieldSpecified;
        
        private string dataOriginFlagField;
        
        private string editIdField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string localtionIdField;
        
        private string mainIdField;
        
        private string matTypeField;
        
        private string materCodeField;
        
        private string materLocationField;
        
        private string materNameField;
        
        private string materTypeField;
        
        private string nonhandnumField;
        
        private string occurQtyField;
        
        private double oddQtyField;
        
        private bool oddQtyFieldSpecified;
        
        private double packingNumbersField;
        
        private bool packingNumbersFieldSpecified;
        
        private string pkMeasdocField;
        
        private string remarkField;
        
        private double substanceField;
        
        private bool substanceFieldSpecified;
        
        private string unitCodeField;
        
        private string unitNameField;
        
        private string warehouseCodeField;
        
        private string warehouseNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string auditMark {
            get {
                return this.auditMarkField;
            }
            set {
                this.auditMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double batchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool batchNumberSpecified {
            get {
                return this.batchNumberFieldSpecified;
            }
            set {
                this.batchNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double costprice {
            get {
                return this.costpriceField;
            }
            set {
                this.costpriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costpriceSpecified {
            get {
                return this.costpriceFieldSpecified;
            }
            set {
                this.costpriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataOriginFlag {
            get {
                return this.dataOriginFlagField;
            }
            set {
                this.dataOriginFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string editId {
            get {
                return this.editIdField;
            }
            set {
                this.editIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string localtionId {
            get {
                return this.localtionIdField;
            }
            set {
                this.localtionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mainId {
            get {
                return this.mainIdField;
            }
            set {
                this.mainIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string matType {
            get {
                return this.matTypeField;
            }
            set {
                this.matTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materCode {
            get {
                return this.materCodeField;
            }
            set {
                this.materCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materLocation {
            get {
                return this.materLocationField;
            }
            set {
                this.materLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materName {
            get {
                return this.materNameField;
            }
            set {
                this.materNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materType {
            get {
                return this.materTypeField;
            }
            set {
                this.materTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nonhandnum {
            get {
                return this.nonhandnumField;
            }
            set {
                this.nonhandnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string occurQty {
            get {
                return this.occurQtyField;
            }
            set {
                this.occurQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double oddQty {
            get {
                return this.oddQtyField;
            }
            set {
                this.oddQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oddQtySpecified {
            get {
                return this.oddQtyFieldSpecified;
            }
            set {
                this.oddQtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double packingNumbers {
            get {
                return this.packingNumbersField;
            }
            set {
                this.packingNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool packingNumbersSpecified {
            get {
                return this.packingNumbersFieldSpecified;
            }
            set {
                this.packingNumbersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pkMeasdoc {
            get {
                return this.pkMeasdocField;
            }
            set {
                this.pkMeasdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double substance {
            get {
                return this.substanceField;
            }
            set {
                this.substanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool substanceSpecified {
            get {
                return this.substanceFieldSpecified;
            }
            set {
                this.substanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unitCode {
            get {
                return this.unitCodeField;
            }
            set {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string warehouseCode {
            get {
                return this.warehouseCodeField;
            }
            set {
                this.warehouseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string warehouseName {
            get {
                return this.warehouseNameField;
            }
            set {
                this.warehouseNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class materInAndOutVO {
        
        private string loginnameField;
        
        private string nameField;
        
        private string vouNoField;
        
        private string planNoField;
        
        private string prodCodeField;
        
        private string shiftCodeField;
        
        private string teamCodeField;
        
        private System.DateTime fDateField;
        
        private bool fDateFieldSpecified;
        
        private string shopCodeField;
        
        private string createIdField;
        
        private string creatorField;
        
        private string modifyIdField;
        
        private string modifyManField;
        
        private string modifyTimeField;
        
        private string auditMarkField;
        
        private double batchNumberField;
        
        private bool batchNumberFieldSpecified;
        
        private double caboSumField;
        
        private bool caboSumFieldSpecified;
        
        private double piecesSumField;
        
        private bool piecesSumFieldSpecified;
        
        private string remarkField;
        
        private string inoutTypeField;
        
        private string bomTypeField;
        
        private string cwarehouseidField;
        
        private string cwarehousenameField;
        
        private string isNcField;
        
        private long formulaIdField;
        
        private bool formulaIdFieldSpecified;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private string shiftNameField;
        
        private string teamNameField;
        
        private string prodNameField;
        
        private tShopMaterInoutSub[] subListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string loginname {
            get {
                return this.loginnameField;
            }
            set {
                this.loginnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vouNo {
            get {
                return this.vouNoField;
            }
            set {
                this.vouNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string planNo {
            get {
                return this.planNoField;
            }
            set {
                this.planNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string prodCode {
            get {
                return this.prodCodeField;
            }
            set {
                this.prodCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shiftCode {
            get {
                return this.shiftCodeField;
            }
            set {
                this.shiftCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string teamCode {
            get {
                return this.teamCodeField;
            }
            set {
                this.teamCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime FDate {
            get {
                return this.fDateField;
            }
            set {
                this.fDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FDateSpecified {
            get {
                return this.fDateFieldSpecified;
            }
            set {
                this.fDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shopCode {
            get {
                return this.shopCodeField;
            }
            set {
                this.shopCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string createId {
            get {
                return this.createIdField;
            }
            set {
                this.createIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modifyId {
            get {
                return this.modifyIdField;
            }
            set {
                this.modifyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modifyMan {
            get {
                return this.modifyManField;
            }
            set {
                this.modifyManField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modifyTime {
            get {
                return this.modifyTimeField;
            }
            set {
                this.modifyTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string auditMark {
            get {
                return this.auditMarkField;
            }
            set {
                this.auditMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double batchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool batchNumberSpecified {
            get {
                return this.batchNumberFieldSpecified;
            }
            set {
                this.batchNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double caboSum {
            get {
                return this.caboSumField;
            }
            set {
                this.caboSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool caboSumSpecified {
            get {
                return this.caboSumFieldSpecified;
            }
            set {
                this.caboSumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double piecesSum {
            get {
                return this.piecesSumField;
            }
            set {
                this.piecesSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool piecesSumSpecified {
            get {
                return this.piecesSumFieldSpecified;
            }
            set {
                this.piecesSumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inoutType {
            get {
                return this.inoutTypeField;
            }
            set {
                this.inoutTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bomType {
            get {
                return this.bomTypeField;
            }
            set {
                this.bomTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cwarehouseid {
            get {
                return this.cwarehouseidField;
            }
            set {
                this.cwarehouseidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cwarehousename {
            get {
                return this.cwarehousenameField;
            }
            set {
                this.cwarehousenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isNc {
            get {
                return this.isNcField;
            }
            set {
                this.isNcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long formulaId {
            get {
                return this.formulaIdField;
            }
            set {
                this.formulaIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formulaIdSpecified {
            get {
                return this.formulaIdFieldSpecified;
            }
            set {
                this.formulaIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shiftName {
            get {
                return this.shiftNameField;
            }
            set {
                this.shiftNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string teamName {
            get {
                return this.teamNameField;
            }
            set {
                this.teamNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string prodName {
            get {
                return this.prodNameField;
            }
            set {
                this.prodNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tShopMaterInoutSub[] subList {
            get {
                return this.subListField;
            }
            set {
                this.subListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void yuanfuCgrkCompletedEventHandler(object sender, yuanfuCgrkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class yuanfuCgrkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal yuanfuCgrkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void yuanliaoInAndOut4ws_03CompletedEventHandler(object sender, yuanliaoInAndOut4ws_03CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class yuanliaoInAndOut4ws_03CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal yuanliaoInAndOut4ws_03CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsRespond Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsRespond)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void insertMaterialPurchaseinInfoCompletedEventHandler(object sender, insertMaterialPurchaseinInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertMaterialPurchaseinInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertMaterialPurchaseinInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591