//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MSYS.Web.EquipService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EquipServiceInterfaceServiceSoapBinding", Namespace="http://webservice.dhcc.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseVO))]
    public partial class EquipServiceInterfaceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getMaintainSignRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEquipListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEquipClsListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EquipServiceInterfaceService() {
            this.Url = global::MSYS.Web.Properties.Settings.Default.MSYS_Web_EquipService_EquipServiceInterfaceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getMaintainSignRecordCompletedEventHandler getMaintainSignRecordCompleted;
        
        /// <remarks/>
        public event getEquipListCompletedEventHandler getEquipListCompleted;
        
        /// <remarks/>
        public event getEquipClsListCompletedEventHandler getEquipClsListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.dhcc.com/", ResponseNamespace="http://webservice.dhcc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public maintainSignVO[] getMaintainSignRecord([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("getMaintainSignRecord", new object[] {
                        arg0});
            return ((maintainSignVO[])(results[0]));
        }
        
        /// <remarks/>
        public void getMaintainSignRecordAsync(string arg0) {
            this.getMaintainSignRecordAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getMaintainSignRecordAsync(string arg0, object userState) {
            if ((this.getMaintainSignRecordOperationCompleted == null)) {
                this.getMaintainSignRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMaintainSignRecordOperationCompleted);
            }
            this.InvokeAsync("getMaintainSignRecord", new object[] {
                        arg0}, this.getMaintainSignRecordOperationCompleted, userState);
        }
        
        private void OngetMaintainSignRecordOperationCompleted(object arg) {
            if ((this.getMaintainSignRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMaintainSignRecordCompleted(this, new getMaintainSignRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.dhcc.com/", ResponseNamespace="http://webservice.dhcc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tEqEqpTbl[] getEquipList([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] tEqEqpTbl arg0) {
            object[] results = this.Invoke("getEquipList", new object[] {
                        arg0});
            return ((tEqEqpTbl[])(results[0]));
        }
        
        /// <remarks/>
        public void getEquipListAsync(tEqEqpTbl arg0) {
            this.getEquipListAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getEquipListAsync(tEqEqpTbl arg0, object userState) {
            if ((this.getEquipListOperationCompleted == null)) {
                this.getEquipListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEquipListOperationCompleted);
            }
            this.InvokeAsync("getEquipList", new object[] {
                        arg0}, this.getEquipListOperationCompleted, userState);
        }
        
        private void OngetEquipListOperationCompleted(object arg) {
            if ((this.getEquipListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEquipListCompleted(this, new getEquipListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.dhcc.com/", ResponseNamespace="http://webservice.dhcc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tEqEqpCls[] getEquipClsList([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contentXml) {
            object[] results = this.Invoke("getEquipClsList", new object[] {
                        contentXml});
            return ((tEqEqpCls[])(results[0]));
        }
        
        /// <remarks/>
        public void getEquipClsListAsync(string contentXml) {
            this.getEquipClsListAsync(contentXml, null);
        }
        
        /// <remarks/>
        public void getEquipClsListAsync(string contentXml, object userState) {
            if ((this.getEquipClsListOperationCompleted == null)) {
                this.getEquipClsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEquipClsListOperationCompleted);
            }
            this.InvokeAsync("getEquipClsList", new object[] {
                        contentXml}, this.getEquipClsListOperationCompleted, userState);
        }
        
        private void OngetEquipClsListOperationCompleted(object arg) {
            if ((this.getEquipClsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEquipClsListCompleted(this, new getEquipClsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class maintainSignVO : maintainPlanDetail {
        
        private System.DateTime operateDateField;
        
        private bool operateDateFieldSpecified;
        
        private System.DateTime searchEndField;
        
        private bool searchEndFieldSpecified;
        
        private System.DateTime searchStartField;
        
        private bool searchStartFieldSpecified;
        
        private System.DateTime signDateField;
        
        private bool signDateFieldSpecified;
        
        private string signUserNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime operateDate {
            get {
                return this.operateDateField;
            }
            set {
                this.operateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operateDateSpecified {
            get {
                return this.operateDateFieldSpecified;
            }
            set {
                this.operateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime searchEnd {
            get {
                return this.searchEndField;
            }
            set {
                this.searchEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchEndSpecified {
            get {
                return this.searchEndFieldSpecified;
            }
            set {
                this.searchEndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime searchStart {
            get {
                return this.searchStartField;
            }
            set {
                this.searchStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchStartSpecified {
            get {
                return this.searchStartFieldSpecified;
            }
            set {
                this.searchStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime signDate {
            get {
                return this.signDateField;
            }
            set {
                this.signDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signDateSpecified {
            get {
                return this.signDateFieldSpecified;
            }
            set {
                this.signDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signUserName {
            get {
                return this.signUserNameField;
            }
            set {
                this.signUserNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(maintainSignVO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class maintainPlanDetail : baseVO {
        
        private string checkUserNameField;
        
        private string col1Field;
        
        private string detailTypeField;
        
        private string dutyUserNameField;
        
        private System.DateTime endWorkField;
        
        private bool endWorkFieldSpecified;
        
        private string endWorkStrField;
        
        private string equipIdField;
        
        private string equipNameField;
        
        private string equipNoField;
        
        private string equipTagField;
        
        private System.DateTime firstWorkField;
        
        private bool firstWorkFieldSpecified;
        
        private string firstWorkStrField;
        
        private string idField;
        
        private sbyte isDelField;
        
        private bool isDelFieldSpecified;
        
        private System.DateTime lastOperateTimeField;
        
        private bool lastOperateTimeFieldSpecified;
        
        private System.DateTime lastSignTimeField;
        
        private bool lastSignTimeFieldSpecified;
        
        private string lifeField;
        
        private int lifeDayField;
        
        private bool lifeDayFieldSpecified;
        
        private string mainIdField;
        
        private string maintainAreaField;
        
        private string maintainContentField;
        
        private string maintainReasonField;
        
        private string maintainStepField;
        
        private string operatorIdField;
        
        private string operatorNameField;
        
        private string planYearField;
        
        private string remarkField;
        
        private string stateCodeField;
        
        private string stateNameField;
        
        private int totalOperateCountField;
        
        private bool totalOperateCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string checkUserName {
            get {
                return this.checkUserNameField;
            }
            set {
                this.checkUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string col1 {
            get {
                return this.col1Field;
            }
            set {
                this.col1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detailType {
            get {
                return this.detailTypeField;
            }
            set {
                this.detailTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dutyUserName {
            get {
                return this.dutyUserNameField;
            }
            set {
                this.dutyUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime endWork {
            get {
                return this.endWorkField;
            }
            set {
                this.endWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endWorkSpecified {
            get {
                return this.endWorkFieldSpecified;
            }
            set {
                this.endWorkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endWorkStr {
            get {
                return this.endWorkStrField;
            }
            set {
                this.endWorkStrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipId {
            get {
                return this.equipIdField;
            }
            set {
                this.equipIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipName {
            get {
                return this.equipNameField;
            }
            set {
                this.equipNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipNo {
            get {
                return this.equipNoField;
            }
            set {
                this.equipNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipTag {
            get {
                return this.equipTagField;
            }
            set {
                this.equipTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime firstWork {
            get {
                return this.firstWorkField;
            }
            set {
                this.firstWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool firstWorkSpecified {
            get {
                return this.firstWorkFieldSpecified;
            }
            set {
                this.firstWorkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstWorkStr {
            get {
                return this.firstWorkStrField;
            }
            set {
                this.firstWorkStrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sbyte isDel {
            get {
                return this.isDelField;
            }
            set {
                this.isDelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isDelSpecified {
            get {
                return this.isDelFieldSpecified;
            }
            set {
                this.isDelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime lastOperateTime {
            get {
                return this.lastOperateTimeField;
            }
            set {
                this.lastOperateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastOperateTimeSpecified {
            get {
                return this.lastOperateTimeFieldSpecified;
            }
            set {
                this.lastOperateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime lastSignTime {
            get {
                return this.lastSignTimeField;
            }
            set {
                this.lastSignTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastSignTimeSpecified {
            get {
                return this.lastSignTimeFieldSpecified;
            }
            set {
                this.lastSignTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string life {
            get {
                return this.lifeField;
            }
            set {
                this.lifeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int lifeDay {
            get {
                return this.lifeDayField;
            }
            set {
                this.lifeDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lifeDaySpecified {
            get {
                return this.lifeDayFieldSpecified;
            }
            set {
                this.lifeDayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mainId {
            get {
                return this.mainIdField;
            }
            set {
                this.mainIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maintainArea {
            get {
                return this.maintainAreaField;
            }
            set {
                this.maintainAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maintainContent {
            get {
                return this.maintainContentField;
            }
            set {
                this.maintainContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maintainReason {
            get {
                return this.maintainReasonField;
            }
            set {
                this.maintainReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maintainStep {
            get {
                return this.maintainStepField;
            }
            set {
                this.maintainStepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string planYear {
            get {
                return this.planYearField;
            }
            set {
                this.planYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stateName {
            get {
                return this.stateNameField;
            }
            set {
                this.stateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int totalOperateCount {
            get {
                return this.totalOperateCountField;
            }
            set {
                this.totalOperateCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalOperateCountSpecified {
            get {
                return this.totalOperateCountFieldSpecified;
            }
            set {
                this.totalOperateCountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tEqEqpTbl))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(maintainPlanDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(maintainSignVO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class baseVO {
        
        private int drawField;
        
        private bool drawFieldSpecified;
        
        private int lengthField;
        
        private bool lengthFieldSpecified;
        
        private int pageNumField;
        
        private bool pageNumFieldSpecified;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int draw {
            get {
                return this.drawField;
            }
            set {
                this.drawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool drawSpecified {
            get {
                return this.drawFieldSpecified;
            }
            set {
                this.drawFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageNum {
            get {
                return this.pageNumField;
            }
            set {
                this.pageNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumSpecified {
            get {
                return this.pageNumFieldSpecified;
            }
            set {
                this.pageNumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class tEqEqpCls {
        
        private string idKeyField;
        
        private string nodeNameField;
        
        private string nodeValueField;
        
        private string parentIdField;
        
        private string pathField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idKey {
            get {
                return this.idKeyField;
            }
            set {
                this.idKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nodeName {
            get {
                return this.nodeNameField;
            }
            set {
                this.nodeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nodeValue {
            get {
                return this.nodeValueField;
            }
            set {
                this.nodeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.dhcc.com/")]
    public partial class tEqEqpTbl : baseVO {
        
        private string clsCodeField;
        
        private string clsNameField;
        
        private string createTimeField;
        
        private string creatorField;
        
        private string dutyNameField;
        
        private string eqModelField;
        
        private string eqNameField;
        
        private string eqStatusField;
        
        private string eqTypeField;
        
        private string eqpFromField;
        
        private string eqpIpField;
        
        private string eqpMacField;
        
        private string eqpSnField;
        
        private string eqpSysField;
        
        private string financeEqNameField;
        
        private int flagField;
        
        private string idkeyField;
        
        private string isDelField;
        
        private string isMadeinchinaField;
        
        private string isSpecEqpField;
        
        private string manufacturerField;
        
        private string mgtDeptCodeField;
        
        private string mgtDeptNameField;
        
        private string ncCodeField;
        
        private string netWorthField;
        
        private string oriOwnerNameField;
        
        private string oriWorthField;
        
        private string ownerNameField;
        
        private string powerUnitField;
        
        private string ratedPowerField;
        
        private string realPowerField;
        
        private string remarkField;
        
        private string serialNumberField;
        
        private string sgsCodeField;
        
        private string supplierField;
        
        private string useDeptCodeField;
        
        private string useDeptNameField;
        
        private string usedDateField;
        
        private string zgDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsCode {
            get {
                return this.clsCodeField;
            }
            set {
                this.clsCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsName {
            get {
                return this.clsNameField;
            }
            set {
                this.clsNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string createTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dutyName {
            get {
                return this.dutyNameField;
            }
            set {
                this.dutyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eqModel {
            get {
                return this.eqModelField;
            }
            set {
                this.eqModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eqName {
            get {
                return this.eqNameField;
            }
            set {
                this.eqNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eqStatus {
            get {
                return this.eqStatusField;
            }
            set {
                this.eqStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eqType {
            get {
                return this.eqTypeField;
            }
            set {
                this.eqTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eqpFrom {
            get {
                return this.eqpFromField;
            }
            set {
                this.eqpFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eqpIp {
            get {
                return this.eqpIpField;
            }
            set {
                this.eqpIpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eqpMac {
            get {
                return this.eqpMacField;
            }
            set {
                this.eqpMacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eqpSn {
            get {
                return this.eqpSnField;
            }
            set {
                this.eqpSnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eqpSys {
            get {
                return this.eqpSysField;
            }
            set {
                this.eqpSysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string financeEqName {
            get {
                return this.financeEqNameField;
            }
            set {
                this.financeEqNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idkey {
            get {
                return this.idkeyField;
            }
            set {
                this.idkeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isDel {
            get {
                return this.isDelField;
            }
            set {
                this.isDelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isMadeinchina {
            get {
                return this.isMadeinchinaField;
            }
            set {
                this.isMadeinchinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isSpecEqp {
            get {
                return this.isSpecEqpField;
            }
            set {
                this.isSpecEqpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mgtDeptCode {
            get {
                return this.mgtDeptCodeField;
            }
            set {
                this.mgtDeptCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mgtDeptName {
            get {
                return this.mgtDeptNameField;
            }
            set {
                this.mgtDeptNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ncCode {
            get {
                return this.ncCodeField;
            }
            set {
                this.ncCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string netWorth {
            get {
                return this.netWorthField;
            }
            set {
                this.netWorthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oriOwnerName {
            get {
                return this.oriOwnerNameField;
            }
            set {
                this.oriOwnerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oriWorth {
            get {
                return this.oriWorthField;
            }
            set {
                this.oriWorthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ownerName {
            get {
                return this.ownerNameField;
            }
            set {
                this.ownerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string powerUnit {
            get {
                return this.powerUnitField;
            }
            set {
                this.powerUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ratedPower {
            get {
                return this.ratedPowerField;
            }
            set {
                this.ratedPowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string realPower {
            get {
                return this.realPowerField;
            }
            set {
                this.realPowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sgsCode {
            get {
                return this.sgsCodeField;
            }
            set {
                this.sgsCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string useDeptCode {
            get {
                return this.useDeptCodeField;
            }
            set {
                this.useDeptCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string useDeptName {
            get {
                return this.useDeptNameField;
            }
            set {
                this.useDeptNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usedDate {
            get {
                return this.usedDateField;
            }
            set {
                this.usedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zgDate {
            get {
                return this.zgDateField;
            }
            set {
                this.zgDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void getMaintainSignRecordCompletedEventHandler(object sender, getMaintainSignRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMaintainSignRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMaintainSignRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public maintainSignVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((maintainSignVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void getEquipListCompletedEventHandler(object sender, getEquipListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEquipListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEquipListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tEqEqpTbl[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tEqEqpTbl[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void getEquipClsListCompletedEventHandler(object sender, getEquipClsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEquipClsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEquipClsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tEqEqpCls[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tEqEqpCls[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591